#!/bin/bash

# Teamviewer launcher will launch the Teamviewer application or 
# will download and install it if not installed yet 
# Created by Paweł "pavroo" Pijanowski 2015/08/27
# Copyright 2015-2018 under the GNU GPL2 License
# Last update 2018/03/16

if [ -f /usr/bin/teamviewer ]; then
	/usr/bin/teamviewer

	exit 0

else
	/usr/bin/remsu /opt/sparky-teamviewer/teamviewer-installer

	exit 0
fi

exit 0
