#!/bin/bash

# Teamviewer On-Line Installer is a script which can download and install Teamviewer for Linux (Debian package)
# Created by Paweł "pavroo" Pijanowski 2015/08/27
# Copyright 2015-2018 under the GNU GPL2 License
# Last updated 2018/04/01

# get default's locale file
DEFLOCDIR="/usr/share/sparky/sparky-teamviewer"
if [ "`cat /etc/default/locale | grep de_DE`" != "" ]; then
. $DEFLOCDIR/de
elif [ "`cat /etc/default/locale | grep es_AR`" != "" ]; then
. $DEFLOCDIR/es
elif [ "`cat /etc/default/locale | grep fr_FR`" != "" ]; then
. $DEFLOCDIR/fr
elif [ "`cat /etc/default/locale | grep it_IT`" != "" ]; then
. $DEFLOCDIR/it
elif [ "`cat /etc/default/locale | grep ja_JP`" != "" ]; then
. $DEFLOCDIR/ja
elif [ "`cat /etc/default/locale | grep pl_PL`" != "" ]; then
. $DEFLOCDIR/pl
elif [ "`cat /etc/default/locale | grep pt_BR`" != "" ]; then
. $DEFLOCDIR/pt_BR
elif [ "`cat /etc/default/locale | grep pt_PT`" != "" ]; then
. $DEFLOCDIR/pt_PT
elif [ "`cat /etc/default/locale | grep sv_SE`" != "" ]; then
. $DEFLOCDIR/se
else
. $DEFLOCDIR/en
fi

testroot="`whoami`"
if [ "$testroot" != "root" ]; then
	/usr/bin/remsu $0 &
fi

DIALOG="yad --window-icon=text-x-script --width=450 --height=200 --center"
TITLE="--always-print-result --dialog-sep --image=text-x-script --title="
TEXT="--text="
OKEXIT=" --button=Ok:0 --button=$LOCAL1:1 "
MSGBOX=" --button=Ok:0 "
MENU="--list --column=$LOCAL2 --column=$LOCAL3"
TITLETEXT="$LOCAL4"
if [ -f /usr/bin/sparky-xterm ];then
	SPARKYXTERM="/usr/bin/sparky-xterm"
else
	echo "sparky-xterm is missing... Exiting..."
	exit 1
fi

# check internet connection
PINGTEST=$(ping -c 1 debian.org | grep [0-9])

if [ "$PINGTEST" = "" ]; then

	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL5"
	exit 1
fi

$DIALOG $TITLE"$TITLETEXT" $OKEXIT $TEXT"$LOCAL6"

if [ "$?" != "0" ]; then

	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL7"
	exit 1

else

	$SPARKYXTERM "apt-get update"
	$SPARKYXTERM "apt-get install teamviewer"
	$SPARKYXTERM "apt-get install -f"

fi

# check has the application been installed
if [ -f /usr/bin/teamviewer ]; then

	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL8"

	/usr/bin/teamviewer
	exit 0
else

	$DIALOG $TITLE"$TITLETEXT" $MSGBOX $TEXT"$LOCAL9"
	exit 0
fi

exit 0
