#!/bin/bash

# Teamviewer launcher will launch the Teamviewer application or 
# will download and install it if not installed yet 
# Created by Paweł "pavroo" Pijanowski 2015/08/27
# Last update 2015/11/05
# Copyright 2015 under the GNU GPL2 License

if [ -f /usr/bin/teamviewer ]; then
	/usr/bin/teamviewer

	exit 0

else
	/usr/bin/remsu /opt/sparky-teamviewer/teamviewer-installer

	exit 0
fi
